version: '3.8'

services:
  postgres:
    image: postgres:16
    container_name: local-postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: circle_db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: Finbd786
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  postgres-data:
